os: linux
dist: xenial

language: java

jdk:
  - oraclejdk16

services:
  - docker


before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull postgres:13.2-alpine
  - docker run -p 5432:5432 -d -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=dash_test postgres:13.2-alpine
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

before_script:
  - ./gradlew ktlintCheck

script:
  - ./gradlew clean build test -Dspring.profiles.active=test -Dspring.config.location=src/test/resources/application-test.properties

after_success:
  - ./gradlew jacocoTestReport coveralls  --info
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Kotlin -r build/reports/jacoco/test/jacocoTestReport.xml
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash docker_deploy.sh
  skip_cleanup: true
  on:
    branch: master