language: java
os: linux
dist: xenial
jdk:
  - oraclejdk15

services:
  - docker
  - postgresql

addons:
  postgresql: 13
  apt:
    update: true
    packages:
      - postgresql-13
env:
  global:
    - PGPORT=5433
  jobs:
    - DB_PORT=5433 DB_USERNAME=postgres

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

before_script:
  # Use trust instead of peer authentication:
  - psql -p 5433 -c 'create database dash_test;' -U postgres
  - psql -p 5433 -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
  - ./gradlew ktlintCheck

script:
  - ./gradlew clean build test -Dspring.profiles.active=test -Dspring.config.location=src/test/resources/application-test.properties

after_success:
  - ./gradlew jacocoTestReport coveralls
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Kotlin -r build/reports/jacoco/test/jacocoTestReport.xml
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash docker_deploy.sh
  skip_cleanup: true
  on:
    branch: master