# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle CI

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: "16"
          distribution: "adopt"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint
        run: |
          ./gradlew detekt
          ./gradlew ktlintCheck

      - name: Pull mock server
        run: |
          if [[ "$(git ls-remote --heads https://github.com/ArnaudFlaesch/Dash-MockServer ${GITHUB_REF#refs/*/} | wc -l)" == 1 && ${GITHUB_REF#refs/*/} != 'master' && ${GITHUB_REF#refs/*/} != 'master' ]]; then
            docker pull arnaudf93/dashmockserver:${GITHUB_REF#refs/*/}
            docker run -p 5000:5000 -d arnaudf93/dashmockserver:${GITHUB_REF#refs/*/}
          else
            docker pull arnaudf93/dashmockserver:latest
            docker run -p 5000:5000 -d arnaudf93/dashmockserver:latest
          fi

      - name: Build with Gradle
        run: ./gradlew clean build -Dspring.profiles.active=test -Dspring.config.location=src/test/resources/application-test.properties

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test report
          path: build/reports/tests/test

      - name: Report coverage
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Kotlin -r build/reports/jacoco/test/jacocoTestReport.xml --project-token ${{ secrets.CODACY_PROJECT_TOKEN }}
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${{ secrets.CODECOV_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Docker build and push TEST
        if: github.ref != 'refs/heads/master' && !contains(github.ref, 'renovate/')
        run : |
          docker build -t dashwebservices .
          docker tag dashwebservices arnaudf93/dashwebservices:${GITHUB_REF#refs/*/}
          docker push arnaudf93/dashwebservices:${GITHUB_REF#refs/*/}

      - name: Docker build and push DEV
        if: github.ref == 'refs/heads/master'
        run : |
          docker build -t dashwebservices .
          docker tag dashwebservices arnaudf93/dashwebservices:latest
          docker push arnaudf93/dashwebservices:latest
